# fly.toml app configuration file generated for hearchco on 2023-12-03T17:11:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hearchco"
primary_region = "cdg"

[build]
  image = "ghcr.io/hearchco/hearchco:latest"

[env]
  HEARCHCO_SERVER_CACHE_TYPE = "redis"
  HEARCHCO_SERVER_FRONTENDURL = "*"

[http_service]
  internal_port = 3030
  force_https = false # needed for flycast
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 5
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 10
    soft_limit = 5

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
