app = "zadnjica"
primary_region = "cdg"

[build]
  image = "ghcr.io/tminaorg/brzaguza:latest"

[env]
  BRZAGUZA_SERVER_FRONTENDURL = "https://brzaguza.rs"

[mounts]
  source = "data"
  destination = "/config"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 0
    soft_limit = 1
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
